export const ALL_BLOG_REQUEST = "ALL_BLOG_REQUEST ";
export const ALL_BLOG_SUCCESS = "ALL_BLOG_SUCCESS ";
export const ALL_BLOG_FAIL = "ALL_BLOG_FAIL ";
export const CLEAR_ERRORS = "CLEAR_ERRORS ";


export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST ";
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS ";
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL ";
export const BLOG_FILTER = "BLOG_FILTER";


export const LOAD_CREATED_BLOG_REQUEST = "LOAD_CREATED_BLOG_REQUEST ";
export const LOAD_CREATED_BLOG_SUCCESS = "LOAD_CREATED_BLOG_SUCCESS ";
export const LOAD_CREATED_BLOG_FAIL = "LOAD_CREATED_BLOG_FAIL";


export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";
export const CREATE_BLOG_RESET = "CREATE_BLOG_RESET";


export const EDIT_BLOG_REQUEST = 'EDIT_BLOG_REQUEST';
export const EDIT_BLOG_SUCCESS = 'EDIT_BLOG_SUCCESS';
export const EDIT_BLOG_FAIL = 'EDIT_BLOG_FAIL';
export const EDIT_BLOG_RESET = 'EDIT_BLOG_RESET';


export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAIL = 'DELETE_BLOG_FAIL';
export const DELETE_BLOG_RESET = 'DELETE_BLOG_REST';

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'