export const FETCH_INCOMING_ORDER_REQUEST = "FETCH_INCOMING_ORDER_REQUEST";
export const FETCH_INCOMING_ORDER_SUCCESS = "FETCH_INCOMING_ORDER_SUCCESS";
export const FETCH_INCOMING_ORDER_FAIL = "FETCH_INCOMING_ORDER_FAIL";