export const FETCH_INCOMING_ORDER_REQUEST = "FETCH_INCOMING_ORDER_REQUEST";
export const FETCH_INCOMING_ORDER_SUCCESS = "FETCH_INCOMING_ORDER_SUCCESS";
export const FETCH_INCOMING_ORDER_FAIL = "FETCH_INCOMING_ORDER_FAIL";

export const UPDATE_INCOMING_ORDER_STATUS_REQUEST = "UPDATE_INCOMING_ORDER_STATUS_REQUEST";
export const UPDATE_INCOMING_ORDER_STATUS_SUCCESS = "UPDATE_INCOMING_ORDER_STATUS_SUCCESS";
export const UPDATE_INCOMING_ORDER_STATUS_FAIL = "UPDATE_INCOMING_ORDER_STATUS_FAIL";
export const UPDATE_INCOMING_ORDER_STATUS_RESET = "UPDATE_INCOMING_ORDER_STATUS_RESET";
