//place order constants
export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST'
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL'
export const PLACE_ORDER_RESET = 'PLACE_ORDER_RESET'

//order list constants
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET'

//order details constants
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET'

//payment methods constants
export const PAYMENT_METHODS_REQUEST = 'PAYMENT_METHODS_REQUEST'
export const PAYMENT_METHODS_SUCCESS = 'PAYMENT_METHODS_SUCCESS'
export const PAYMENT_METHODS_FAIL = 'PAYMENT_METHODS_FAIL'

//save payment method constants
export const SAVE_PAYMENT_METHOD_REQUEST = 'SAVE_PAYMENT_METHOD_REQUEST'
export const SAVE_PAYMENT_METHOD_SUCCESS = 'SAVE_PAYMENT_METHOD_SUCCESS'
export const SAVE_PAYMENT_METHOD_FAIL = 'SAVE_PAYMENT_METHOD_FAIL'
export const SAVE_PAYMENT_METHOD_RESET = 'SAVE_PAYMENT_METHOD_RESET'

//load user orders constants
export const LOAD_USER_ORDERS_REQUEST = 'LOAD_USER_ORDERS_REQUEST'
export const LOAD_USER_ORDERS_SUCCESS = 'LOAD_USER_ORDERS_SUCCESS'
export const LOAD_USER_ORDERS_FAIL = 'LOAD_USER_ORDERS_FAIL'
export const LOAD_USER_ORDERS_RESET = 'LOAD_USER_ORDERS_RESET'
