export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST ";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS ";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL ";
export const CLEAR_ERRORS = "CLEAR_ERRORS ";

export const ALL_PRODUCT_REQUEST2 = "ALL_PRODUCT_REQUEST ";
export const ALL_PRODUCT_SUCCESS2 = "ALL_PRODUCT_SUCCESS ";
export const ALL_PRODUCT_FAIL2 = "ALL_PRODUCT_FAIL ";
export const CLEAR_ERRORS2 = "CLEAR_ERRORS ";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST ";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS ";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL ";
export const PRODUCT_FILTER = "PRODUCT_FILTER";


export const LOAD_CREATED_PRODUCT_REQUEST = "LOAD_CREATED_PRODUCT_REQUEST ";
export const LOAD_CREATED_PRODUCT_SUCCESS = "LOAD_CREATED_PRODUCT_SUCCESS ";
export const LOAD_CREATED_PRODUCT_FAIL = "LOAD_CREATED_PRODUCT_FAIL";


export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";


export const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_FAIL';
export const EDIT_PRODUCT_RESET = 'EDIT_PRODUCT_RESET';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_REST';

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'