export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST ";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS ";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL ";
export const CLEAR_ERRORS = "CLEAR_ERRORS ";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST ";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS ";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL ";
export const PRODUCT_FILTER = "PRODUCT_FILTER";


export const LOAD_CREATED_PRODUCT_REQUEST = "LOAD_CREATED_PRODUCT_REQUEST ";
export const LOAD_CREATED_PRODUCT_SUCCESS = "LOAD_CREATED_PRODUCT_SUCCESS ";
export const LOAD_CREATED_PRODUCT_FAIL = "LOAD_CREATED_PRODUCT_FAIL";


export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";