export const REGISTER_SELLER_REQUEST = 'REGISTER_SELLER_REQUEST';
export const REGISTER_SELLER_SUCCESS = 'REGISTER_SELLER_SUCCESS';
export const REGISTER_SELLER_FAIL = 'REGISTER_SELLER_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';