export const GET_REQ_SELLER_REQUEST = 'GET_REQ_SELLER_REQUEST';
export const GET_REQ_SELLER_SUCCESS = 'GET_REQ_SELLER_SUCCESS';
export const GET_REQ_SELLER_FAIL = 'GET_REQ_SELLER_FAIL';


export const UPDATE_SELLER_ROLE_REQUEST = 'UPDATE_SELLER_ROLE_REQUEST';
export const UPDATE_SELLER_ROLE_SUCCESS = 'UPDATE_SELLER_ROLE_SUCCESS';
export const UPDATE_SELLER_ROLE_FAIL = 'UPDATE_SELLER_ROLE_FAIL';
export const UPDATE_SELLER_ROLE_RESET= 'UPDATE_SELLER_ROLE_RESET';



export const CLEAR_ERRORS = 'CLEAR_ERRORS';

