export const LOGIN_REQUEST = "LOGIN_REQUEST ";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS ";
export const LOGIN_FAIL = "LOGIN_FAIL ";

export const REGISTER_REQUEST = "REGISTER_REQUEST ";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS ";
export const REGISTER_FAIL = "REGISTER_FAIL ";

export const USER_VERIFY_REQUEST = 'USER_VERIFY_REQUEST';
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS';
export const USER_VERIFY_WRONG_ATTEMP = 'USER_VERIFY_WRONG_ATTEMP';
export const USER_VERIFY_FAIL = 'USER_VERIFY_FAIL';


export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST ";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS ";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL ";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS ";
export const LOGOUT_FAIL = "LOGOUT_FAIL ";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const UPDATE_USER_PASSWORD_REQUEST = "UPDATE_USER_PASSWORD_REQUEST";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_FAIL = "UPDATE_USER_PASSWORD_FAIL";
export const UPDATE_USER_PASSWORD_RESET = "UPDATE_USER_PASSWORD_RESET";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST ";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS ";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL ";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST ";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS ";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL ";

export const CLEAR_POPUP_MESSAGE = "CLEAR_POPUP_MESSAGE";
export const CLEAR_ERRORS = "CLEAR_ERRORS ";